// all values are in blankmynt
var DATA = {"currencies": [
    {"name": "Sheets",
     "area": "Alliath",
     "types": [{"name": "Sheets",
                "value": 0.005}]},

    {"name": "Pins",
     "area": "Blenkt, Ceall",
     "types": [{"name": "Saffirpins",
                "value": 1.3},
               {"name": "Smaragdpins",
                "value": 0.8},
               {"name": "Rubinpins",
                "value": 0.4},
               {"name": "Cobberpins",
                "value": 0.1}]},

    {"name": "Jølva",
     "area": "Cerya",
     "types": [{"name": "Jølva",
                "value": 0.06}]},

    {"name": "Blankmynt",
     "area": "Ekko, Hilarth",
     "types": [{"name": "Blankmynt",
                "value": 1},
               {"name": "Havmynt",
                "value": 0.1},
               {"name": "Blodmynt",
                "value": 0.01}]},

    {"name": "Dia",
     "area": "Favoloun",
     "types": [{"name": "Dia",
                "value": 4.51},
               {"name": "Gos",
                "value": 3.34},
               {"name": "So",
                "value": 2.13},
               {"name": "Cop",
                "value": 1.21},
               {"name": "Tin",
                "value": 0.59},
               {"name": "Lo",
                "value": 0.02}]},

    {"name": "Stormer",
     "area": "Flood",
     "types": [{"name": "Stormer",
                "value": 0.13}]},

    {"name": "Muja",
     "area": "Gwan-dey",
     "types": [{"name": "Muja",
                "value": 1.8}]},

    {"name": "Myakik",
     "area": "Juvanti",
     "types": [{"name": "Myakik",
                "value": 2}]},

    {"name": "Sølvmynt",
     "area": "Naiiva",
     "types": [{"name": "Sølvmynt",
                "value": 0.3},
               {"name": "Halvsølv",
                "value": 0.05}]},

    {"name": "Tao",
     "area": "Senalis",
     "types": [{"name": "Enhjørningtao",
                "value": 997.3},
               {"name": "Titantao",
                "value": 102},
               {"name": "Onyxtao",
                "value": 47},
               {"name": "Eifelbeintao",
                "value": 23},
               {"name": "Gulltao",
                "value": 1.4},
               {"name": "Sølvtao",
                "value": 0.31},
               {"name": "Bronsetao",
                "value": 0.11},
               {"name": "Cobbertao",
                "value": 0.04}]},

    {"name": "Edeler",
     "area": "Stormdalen",
     "types": [{"name": "Edeler",
                "value": 3.312}]},

    {"name": "Stenger",
     "area": "Treek",
     "types": [{"name": "Helstenger",
                "value": 10.3},
               {"name": "Halvstenger",
                "value": 5.15},
               {"name": "Kvartstenger",
                "value": 2.575},
               {"name": "Tomme",
                "value": 1.2875},
               {"name": "Finger",
                "value": 0.64375},
               {"name": "Mini",
                "value": 0.321875},
               {"name": "Bondestenger",
                "value": 0.1609375}]},

    {"name": "Strømledere",
     "area": "Veija",
     "types": [{"name": "Strømledere",
                "value": 1.83},
               {"name": "Halve Strømledere",
                "value": 1.83/2},
               {"name": "Kvarte Strømledere",
                "value": 1.83/4},
               {"name": "Ottendedels-strømledere",
                "value": 1.83/8}]},

    {"name": "Gullminner",
     "area": "Wakiliath",
     "types": [{"name": "Gullminner",
                "value": 10.655}]},

    {"name": "Diviniteter",
     "area": "Xera",
     "types": [{"name": "Diviniteter",
                "value": 0.2}]},
]}